### PR TITLE
Stack update + PWA Notification

### PR DESCRIPTION
**Pull request by Awesome-E**
- Eslint
- Parcel so you can use SCSS, typescript, and npm packages in the web with `import` syntax
- `npm run dev` will also automatically start a HMR server (hot module replacement // hot reload)

Build will currently be broken because it goes to a different folder

### CODE REVIEW

**Comment by Awesome-E** [comment]
Quick note, you will need to do `sub.unsubscribe()` on any browsers where you have already subscribed to notifications. This is because the `applicationServerId` has changed.

**Review by anthonyj33 — APPROVED** [review]
Looks good. Thanks sm!

**Comment by anthonyj33** [comment]
> Quick note, you will need to do `sub.unsubscribe()` on any browsers where you have already subscribed to notifications. This is because the `applicationServerId` has changed.

Alr sounds good

**Comment by Awesome-E** [comment]
@anthonyj33 squash, merge commit, or rebase?

**Comment by anthonyj33** [comment]
> @anthonyj33 squash, merge commit, or rebase?
> 
> 

Squash and merge to PWA

**Pull request merged**
